### ISSUE TITLE
make some update on home page

### ISSUE THREAD

**Issue by lalitsunar03** [lalitsunar03/Water-Billing-System#1]
find out the issue and let me know

**Comment by lalitsunar03** [comment]
I have updated in home.html page

**Comment by AnilKarki11** [comment]
> find out the issue and let me know

Let's do some change in home page.

**Comment by lalitsunar03** [comment]
okey i will do that change very soon.

**Comment by lalitsunar03** [comment]
change is done as per the issue
bf26beb3464005bec306f226a10b80dec1c4317d
